version: '2'

services:
  curdnodeapp:
    container_name: mtnodeapp
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      # - redis
      - mysql
    restart: always
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3

  # redis:
  #   image: docker.io/bitnami/redis:6.2
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - '6379:6379'
  #   healthcheck:
  #     test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 3
  #   restart: always

  mysql:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'ritul'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - '6661:3306'
    healthcheck:
      test:
        [
          "CMD",
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD'
        ]
      interval: 10s
      timeout: 10s
      retries: 3


